### ISSUE TITLE
Can't access global variable, as if not seen, but in fact it is seen

### ISSUE THREAD

**Issue by ianxek** [jondgoodwin/cone#48] opened 2022-01-10 21:37 UTC
This fails saying `x` is not defined

```
mut x i32

fn main():
  x = 7
```

but this shows that the `x` is seen by the compiler because he complains of type inadequacy in that case

```
mut x i32

fn main():
  x = 7.4
```

**Comment by jondgoodwin** [comment] 2022-01-15 04:01
I tested this out. You are actually getting this error from the linker, not the compiler.  The problem is due to not providing an initial value to global variable x. In a C-like way, the compiler assumes you are initializing it elsewhere, which of course you are not.

Change it to `mut x i32 = 3` or `mut x = 3` and your error disappears.

I am however leaving this open as a different bug. The Cone compiler should error out over the fact that you have not initialized global variable x, but should.

**Comment by jondgoodwin** [comment] 2022-02-13 02:32
Uninitialized, non-extern global variables are now initialized using the "zero initializer".

This introduces some UB, for now. This will later be addressed by future improvements to the compiler that allow for run-time initialization of global variables, followed by the detection of global variables that are never properly initialized.

**Closed by jondgoodwin** 2022-02-13 02:32 UTC
